name: Check Upwork Jobs

on:
  schedule:
    # Exécute le script toutes les heures
    - cron: '0 * * * *'
  workflow_dispatch:  # Permet de déclencher manuellement le workflow si nécessaire 

jobs:
  fetch-and-notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # Spécifie la version de Node.js à utiliser

    - name: Install dependencies
      run: npm install

    - name: Run Upwork job fetch script
      run: node src/index.js
